# Generated by Django 3.2 on 2021-06-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_token',
            field=models.TextField(max_length=500, unique=True),
        ),
    ]
